<?php
$escape = $this->plugin('escapeHtml');
?>
<!DOCTYPE html>
<html>
<head>
    <style>
    img {
        float: left;
        margin: 3px;
    }
    div#text {
        float: right;
        width: 240px;
    }
    div#text h1 {
        margin-top: 0px;
    }
    </style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div style="width: 450px">
        <div id='text'>
            <h1><a href='<?php echo $page->site()->siteUrl(true); ?>'><?php echo $page->title(); ?></a></h1>
        </div>
        <?php
        foreach ($page->blocks() as $block) {
            foreach ($block->attachments() as $attachment) {
                $item = $attachment->item();
                if ($item && ($primaryMedia = $item->primaryMedia())) {
                    $image = $escape($primaryMedia->thumbnailUrl('square'));
                    echo "<img src='$image'></img>";
                    break 2;
                }
            }
        }
        ?>
    </div>
</body>
</html>
